### ISSUE TITLE
Add other types of characterization

### ISSUE THREAD

**Issue by virtuald** [robotpy/robot-characterization#3]
I really like this methodology for controlling the robot over networktables... it allows the hard logic to be written once for all languages, and simple code can be ran on the robot side. There are probably other useful ways we can use this methodology to help teams control their robot better.

One thing I'm very interested in is measuring information that would allow us to simulate drivetrain turning better.

Other things that could be done are automated programs to compute feed-forward such as in the TalonSRX user manual.

Perhaps utilities for tuning a robot too?

**Comment by Oblarg** [comment]
I've just made an arm characterization branch.  Perhaps someone with a robot handy could test it?

**Comment by virtuald** [comment]
It looks cool. Unfortunately, I don't have a robot available to me.
