### ISSUE TITLE
Make analysis plots more useful

### ISSUE THREAD

**Issue by virtuald** [robotpy/robot-characterization#7]
And if they are already useful... add some description somewhere talking about what they mean. They don't seem particularly meaningful to me at the moment.

**Comment by Oblarg** [comment]
The diagnostic plots that are most useful are:

_Velocity versus time for the quasistatic test._  Shows you how smoothly your quasistatic test went.  This should, ideally, be a straight line.
_Acceleration versus time for the step-voltage test._  Shows you how smoothly your acceleration test went.  This should, ideally, show the acceleration peaking initially (if there's any remaining "ramp up" at the start then the trimming wasn't adequate) and sharply decaying, eventually oscillating around zero.  This is very useful for determining if the robot accelerated too quickly relative to the loop timing and didn't capture enough data points to accurately determine kA.  If this is the case, the test should be re-run with a higher voltage.
_Voltage versus velocity for the quasistatic test._  This should be linear, as discussed in the whitepaper.  The Kv and Intercept values from the best-fit line to this plot should closely agree with those from the multiple regression.
_(Voltage minus velocity*kV) versus acceleration from the step-voltage test._  This should also be linear, though it will have much more noise than the velocity plot.

All of these plots are useful in spotting outliers and glitches in the procedure.  The script should also report the R-squared from the multiple regression as a diagnostic; this should be in the .95+ range.
